{% set name = "blinker" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blinker-{{ version }}.tar.gz
  sha256: a07839c713d30141433647247db269dd896895b0bf56d2362f663496feae562b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core <4
    - pip
  run:
    - python >=3.8

test:
  imports:
    - blinker
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pallets-eco/blinker
  license: MIT
  license_file: LICENSE.rst
  summary: Fast, simple object-to-object and broadcast signaling

extra:
  recipe-maintainers:
    - ocefpaf
    - frol
    - synapticarbors
