{% set version = "1.6.3" %}

package:
  name: blinker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blinker/blinker-{{ version }}.tar.gz
  sha256: 152090d27c1c5c722ee7e48504b02d76502811ce02e1523553b4cf8c8b3d3a8d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - blinker
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pallets-eco/blinker
  license: MIT
  license_file: LICENSE.rst
  summary: Fast, simple object-to-object and broadcast signaling

extra:
  recipe-maintainers:
    - ocefpaf
    - frol
    - synapticarbors
