{% set version = "1.4" %}

package:
    name: blinker
    version: {{ version }}

source:
    fn: blinker-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/b/blinker/blinker-{{ version }}.tar.gz
    sha256: 471aee25f3992bd325afa3772f1063dbdbbca947a041b8b89466dc00d606f8b6

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - blinker

about:
    home: https://pythonhosted.org/blinker/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Fast, simple object-to-object and broadcast signaling
    dev_url: https://github.com/jek/blinker
    doc_url: https://pythonhosted.org/blinker/

extra:
    recipe-maintainers:
        - ocefpaf
